#!/bin/bash

set -e

django_manage () {
  /usr/local/lib/python-virtualenv/QI/bin/python manage.py "$@"
}

echo -e "=== Pulling latest commits ==="
git pull origin master
echo -e "\n\n=== Applying database migrations ==="
django_manage migrate
echo -e "\n\n=== Restarting uWSGI ==="
service uwsgi restart
