#!/bin/bash
# My first script

echo "Hello World!"
i=4441
URL=https://pennstreaty.haverford.edu/qi/api/files/
while [ $i -lt 4538 ]; do
   echo "Trying for $i"
   wget  $URL$i 
   echo "Got it from URL passing to python"
   python get_img.py $i
   echo "Now cleaning up"
   rm $i 
   let i=i+1
done




